export const supportProcesses = {
  refundProcess: {
    title: "Refund Process Documentation",
    steps: [
      {
        step: 1,
        title: "Customer Request",
        description: "Customer emails support@sillynutrition.com or uses dashboard contact form",
        timeframe: "Immediate",
        actions: [
          "Acknowledge receipt within 2 hours",
          "Log request in support system",
          "Send initial response with timeline",
        ],
      },
      {
        step: 2,
        title: "Eligibility Check",
        description: "Verify refund eligibility based on our 30-day policy",
        timeframe: "Within 4 hours",
        actions: [
          "Check subscription start date",
          "Verify payment history",
          "Review any previous refunds",
          "Confirm account status",
        ],
      },
      {
        step: 3,
        title: "Process Refund",
        description: "Process the refund through payment system",
        timeframe: "Within 24 hours",
        actions: [
          "Process refund in Stripe/payment system",
          "Cancel subscription to prevent future charges",
          "Update customer record",
          "Generate refund confirmation",
        ],
      },
      {
        step: 4,
        title: "Customer Communication",
        description: "Send confirmation and follow-up",
        timeframe: "Within 2 hours of processing",
        actions: [
          "Send refund confirmation email",
          "Provide processing timeline (5-7 days)",
          "Offer feedback opportunity",
          "Set follow-up reminder for 10 days",
        ],
      },
      {
        step: 5,
        title: "Follow-up",
        description: "Ensure customer received refund",
        timeframe: "10 days after processing",
        actions: [
          "Check if customer contacted about missing refund",
          "Send follow-up email if no issues reported",
          "Close support ticket",
          "Log feedback if provided",
        ],
      },
    ],
    eligibilityCriteria: [
      "Within 30 days of initial subscription",
      "Account in good standing (no abuse/fraud)",
      "Original payment method still valid",
      "No previous refunds on same account",
    ],
    escalationTriggers: [
      "Refund amount over £200",
      "Customer claims service failure",
      "Technical issues preventing refund",
      "Customer threatens legal action",
    ],
  },

  cancellationProcess: {
    title: "Cancellation Process Documentation",
    steps: [
      {
        step: 1,
        title: "Cancellation Request",
        description: "Customer initiates cancellation via dashboard or email",
        timeframe: "Immediate",
        actions: [
          "Log cancellation request",
          "Identify cancellation reason",
          "Check for retention opportunities",
          "Verify customer identity",
        ],
      },
      {
        step: 2,
        title: "Retention Attempt",
        description: "Offer alternatives before processing cancellation",
        timeframe: "Within 2 hours",
        actions: [
          "Offer plan downgrade if cost is issue",
          "Suggest pause/freeze option",
          "Provide additional support if service issue",
          "Offer discount if appropriate",
        ],
      },
      {
        step: 3,
        title: "Process Cancellation",
        description: "Cancel subscription while maintaining access",
        timeframe: "Within 4 hours if retention declined",
        actions: [
          "Cancel recurring billing in payment system",
          "Set access end date to current period end",
          "Update customer record with cancellation reason",
          "Prepare cancellation confirmation",
        ],
      },
      {
        step: 4,
        title: "Confirmation & Transition",
        description: "Confirm cancellation and explain next steps",
        timeframe: "Within 1 hour of processing",
        actions: [
          "Send cancellation confirmation email",
          "Explain continued access until period end",
          "Provide data export options",
          "Set up win-back email sequence",
        ],
      },
      {
        step: 5,
        title: "Account Deactivation",
        description: "Remove access at end of billing period",
        timeframe: "On billing period end date",
        actions: [
          "Deactivate dashboard access",
          "Archive customer data (90-day retention)",
          "Send final goodbye email",
          "Add to win-back campaign list",
        ],
      },
    ],
    retentionOffers: [
      "Plan downgrade (Coaching → Essential)",
      "Account pause (1-3 months)",
      "50% discount for 3 months",
      "Additional support/customization",
    ],
    commonReasons: [
      "Cost/budget constraints",
      "Not using the service enough",
      "Plans not meeting expectations",
      "Technical difficulties",
      "Life circumstances changed",
    ],
  },

  escalationProcess: {
    title: "Support Escalation Guidelines",
    levels: [
      {
        level: 1,
        title: "First-Line Support",
        description: "Standard customer service team",
        handles: [
          "General questions",
          "Account issues",
          "Basic technical problems",
          "Plan changes",
          "Standard refunds/cancellations",
        ],
        responseTime: "Within 4 hours",
        escalateTo: "Level 2 if unresolved after 24 hours",
      },
      {
        level: 2,
        title: "Senior Support",
        description: "Experienced support specialists",
        handles: [
          "Complex technical issues",
          "Billing disputes",
          "Service complaints",
          "Custom plan requests",
          "Retention cases",
        ],
        responseTime: "Within 8 hours",
        escalateTo: "Management if customer threatens legal action",
      },
      {
        level: 3,
        title: "Management",
        description: "Support manager or founder",
        handles: [
          "Legal threats",
          "Public complaints (social media)",
          "High-value customer issues",
          "Service failure claims",
          "Media inquiries",
        ],
        responseTime: "Within 2 hours",
        escalateTo: "Legal counsel if necessary",
      },
    ],
    escalationTriggers: [
      "Customer unsatisfied after 48 hours",
      "Refund request over £200",
      "Threat of legal action",
      "Public complaint on social media",
      "Technical issue affecting multiple users",
      "Data privacy concern",
    ],
  },
}
